Age
Gender
Chest Pain Type
Resting Blood Pressure
Serum Cholesterol
Fasting Blood Sugar
Resting Electrocardiographic Results
Maximum Heart Rate Achieved
Exercise induced angina
Depression induced by exercise relative to rest
Slope of the Peak Exercise ST Segment
Number of Major Vessels Colored by Fluoroscopy
Thalassemia
Target